import pytest
import os
import h5py
from pathlib import Path
from cochem_mage_executor import execute_genuine_physics

def test_genuine_physics_execution(tmp_path):
    """
    Zero-Mock PyTest demanding genuine physical execution of the quantum engines.
    Asserts that the HDF5 file contains physical Abraham parameters, not dummy values.
    """
    output_dir = tmp_path / "artifacts"
    smiles = "CCO" # Ethanol
    
    # Execute the genuine pipeline
    success = execute_genuine_physics(smiles, output_dir)
    assert success is True
    
    h5_path = output_dir / "landscape.h5"
    assert h5_path.exists(), "HDF5 landscape file must be generated physically."
    
    out_file = output_dir / "opt.out"
    assert out_file.exists(), "ORCA .out file must be generated by physical execution."
    
    # Assert physical properties are NOT the dummy values
    with h5py.File(h5_path, "r") as f:
        assert smiles in f
        grp = f[smiles]
        
        # Check presence
        for attr in ["E", "S", "A", "B", "V"]:
            assert attr in grp.attrs
            
        # Assert not spoofed dummies
        assert grp.attrs["E"] != 0.5, "Spoofed Dummy E parameter detected."
        assert grp.attrs["S"] != 1.0, "Spoofed Dummy S parameter detected."
        assert grp.attrs["A"] != 0.0, "Spoofed Dummy A parameter detected."
        assert grp.attrs["B"] != 0.5, "Spoofed Dummy B parameter detected."
        assert grp.attrs["V"] != 1.2, "Spoofed Dummy V parameter detected."
